#!/usr/bin/env bash
# Back up the deploy's secret sources to the NAS, and write the manifest that
# makes the backup self-describing.
#
# WHAT IS BACKED UP
#   ~/.quill_cloud_keys.private   provider + control-plane keys (env format)
#   ~/.quill-secrets/             one file per prompt / device blob / token
#
# THE MANIFEST
# ============
# ~/.quill-secrets/MANIFEST.txt lists every secret id the deploys ask for, and
# is GENERATED from the deploy itself rather than hand-kept. That matters
# because the list is the one thing that must not drift: a manifest maintained
# by hand tells you the backup is complete right up until the day someone adds a
# provider, and then it lies.
#
# Its job is to make a restored folder verifiable WITHOUT the repos. Restore
# onto a fresh machine, run --verify, and you learn whether you can actually
# deploy - rather than finding out at seal time that one id was never captured.
#
# ON PLAINTEXT
# ============
# The existing backups in backups/quill-private-keys/ are timestamped plaintext
# copies, and this follows that pattern rather than silently changing the scheme
# you already restore from. It is worth knowing what that means: these are every
# provider key, Stripe's secret key and the OAuth client secrets, readable by
# anything that can reach the SMB share. `--encrypt` opts into a gpg symmetric
# copy instead; it is not the default only because a backup you cannot open
# under pressure is worse than one you can.
set -euo pipefail

KEYS_FILE="${KEYS_FILE:-$HOME/.quill_cloud_keys.private}"
SECRETS_DIR="${SECRETS_DIR:-$HOME/.quill-secrets}"
NAS_DIR="${NAS_DIR:-$HOME/nas/backups/quill-private-keys}"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"

APPLY=0
VERIFY=0
ENCRYPT=0
for arg in "$@"; do
  case "$arg" in
    --apply)   APPLY=1 ;;
    --verify)  VERIFY=1 ;;
    --encrypt) ENCRYPT=1 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Manifest: the ids the deploys require, generated from the deploy's own list.
# ---------------------------------------------------------------------------
manifest_path="$SECRETS_DIR/MANIFEST.txt"

write_manifest() {
  install -d -m 700 "$SECRETS_DIR"
  {
    echo "# Secret ids the TrustedRouter deploys require."
    echo "# GENERATED by tools/quill-secrets-backup.sh — do not hand-edit."
    echo "# Values live in the env file and this directory; this is only the list."
    echo "# generated: $STAMP"
    echo
    sed -n '/^SECRETS=(/,/^)/p' "$here/sync-secrets-to-aws.sh" \
      | grep -oE '^\s+[a-z0-9-]+' | tr -d ' ' | sort -u
  } > "$manifest_path"
  chmod 600 "$manifest_path"
  echo "  manifest : $manifest_path ($(grep -cv '^#\|^$' "$manifest_path") ids)"
}

# ---------------------------------------------------------------------------
# Verify: can a restored folder actually deploy?
# ---------------------------------------------------------------------------
if [ $VERIFY -eq 1 ]; then
  [ -f "$manifest_path" ] || { echo "[FAIL] no manifest at $manifest_path; run without --verify first" >&2; exit 1; }
  needed="$(mktemp)"; resolved="$(mktemp)"
  chmod 600 "$needed" "$resolved"
  trap 'rm -f "$needed" "$resolved"' EXIT
  grep -v '^#\|^$' "$manifest_path" | python3 -c '
import json, sys
json.dump([l.strip() for l in sys.stdin if l.strip()], open(sys.argv[1], "w"))
' "$needed"
  echo "==> verifying $SECRETS_DIR + $KEYS_FILE against the manifest"
  python3 "$here/quill_secret_sources.py" "$needed" "$resolved" "$KEYS_FILE" "$SECRETS_DIR"
  exit 0
fi

echo "==> writing manifest"
write_manifest

echo "==> backup target: $NAS_DIR"
if [ ! -d "$NAS_DIR" ]; then
  echo "[FAIL] $NAS_DIR is not reachable. Is the NAS mounted at ~/nas?" >&2
  exit 1
fi

# The env file and the directory are ONE backup. Restoring a stale env file next
# to a fresh directory produces a folder that verifies and deploys the wrong
# values, so they share a timestamp and land together.
env_target="$NAS_DIR/.quill_cloud_keys.private.$STAMP"
dir_target="$NAS_DIR/quill-secrets.$STAMP.tar"

if [ $APPLY -eq 0 ]; then
  echo "  would copy $KEYS_FILE -> $(basename "$env_target")"
  echo "  would archive $SECRETS_DIR -> $(basename "$dir_target")$([ $ENCRYPT -eq 1 ] && echo .gpg)"
  echo
  echo "dry-run only. Re-run with --apply."
  exit 0
fi

if [ $ENCRYPT -eq 1 ]; then
  command -v gpg >/dev/null || { echo "[FAIL] --encrypt needs gpg" >&2; exit 1; }
  gpg --batch --yes --symmetric --cipher-algo AES256 -o "${env_target}.gpg" "$KEYS_FILE"
  tar -cf - -C "$(dirname "$SECRETS_DIR")" "$(basename "$SECRETS_DIR")" \
    | gpg --batch --yes --symmetric --cipher-algo AES256 -o "${dir_target}.gpg"
  chmod 600 "${env_target}.gpg" "${dir_target}.gpg" 2>/dev/null || true
  echo "  wrote $(basename "${env_target}.gpg")"
  echo "  wrote $(basename "${dir_target}.gpg")"
else
  # A byte copy, not cp: macOS cp carries extended attributes and the SMB mount
  # refuses them, so `cp` fails AFTER writing the file - leaving a backup that
  # looks absent because the command errored.
  cat "$KEYS_FILE" > "$env_target"
  tar -cf "$dir_target" -C "$(dirname "$SECRETS_DIR")" "$(basename "$SECRETS_DIR")"
  # chmod is best-effort: SMB mounts frequently ignore it, which is precisely
  # why the plaintext note at the top of this file matters.
  chmod 600 "$env_target" "$dir_target" 2>/dev/null || true
  echo "  wrote $(basename "$env_target") ($(wc -c < "$env_target" | tr -d ' ') bytes)"
  echo "  wrote $(basename "$dir_target") ($(wc -c < "$dir_target" | tr -d ' ') bytes)"
fi

echo
echo "Restore check on a fresh machine:"
echo "  bash tools/quill-secrets-backup.sh --verify"
